### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by rafush** [ashtonfei/gas-vuematerial-template#1]
thank you for your great work

this template not workink...
the sheet file is empty

**Comment by ashtonfei** [comment]
@rafush Thanks for rasing the issue. It's an issue related to the version of Vue. The default Vue is now at version 3, so it's not working anymore.

update the src link for script tag in the file html/index.html
``` bash
https://unpkg.com/vue@2
```
<img width="662" alt="image" src="https://user-images.githubusercontent.com/16481229/191958812-80aa9d73-131b-486f-b630-a880ff26eb8c.png">

[<img width="1383" alt="image" src="https://user-images.githubusercontent.com/16481229/191959342-bb5a0339-20b0-4edc-a626-7f75e0fcf924.png">](https://script.google.com/macros/s/AKfycbzynVMy-scbUNgyZ69_FrzAivYc2HjXfOabe_J9Kkr2VD4z07Po/exec)
